title: "M3TRIC"
masthead_title: "Monitoreo multiescala y analítica de datos para aplicaciones agrogeoambientales"
description: "Sistema de monitoreo multiescala y analítica de datos para aplicaciones agrogeoambientales"
logo: /images/m3tric_logo.png

# remote_theme: pages-themes/minimal@v0.2.0
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"
locale: "es-CO"

show_downloads: false

header_pages:
  - solucion.md
  - casos.md
  - equipo.md

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

bibliography: /attached/publications.bib
link-citations: true
